library(shiny)
library(shinyjs)
ui <- fluidPage(
  titlePanel("Predict % funded for Kickstarter Project"),
  useShinyjs(),
  sidebarLayout(
    sidebarPanel(
      tabsetPanel(id = "tabset",
                  tabPanel("New Project",
                           textInput("blurb", "Blurb:", "Blurb"),
                           bsTooltip(id = "blurb", title = "Enter a brief description of your project.", 
                                     placement = "right", trigger = "hover"),
                           textInput("caption", "Name:", "Name"),
                           bsTooltip(id = "caption", title = "Give your project a title.", 
                                     placement = "right", trigger = "hover"),
                           selectInput("dataset", "Choose a Genre:", 
                                       choices = c("Flight","Gadgets","Hardware","Makerspaces",
                                                   "Robots",
                                                   "Software",
                                                   "Sound",
                                                   "Space Exploration",
                                                   "Wearables",
                                                   "Web",
                                                   "Experimental",
                                                   "Festivals",
                                                   "Immersive",
                                                   "Musical",
                                                   "Plays",
                                                   "Spaces")),
                           bsTooltip(id = "dataset", title = "Select category for your project", 
                                     placement = "right", trigger = "hover"),
                           sliderInput("goalslider",
                                       "goal amount:",
                                       min = 1,
                                       max = 50000,
                                       value = 1000),
                           bsTooltip(id = "goalslider", title = "Select goal amount for your project", 
                                     placement = "right", trigger = "hover"),
                           sliderInput("durationslider",
                                       "Duration:",
                                       min = 1,
                                       max = 100,
                                       value = 10),
                           bsTooltip(id = "durationslider", title = "Select total duration for your project", 
                                     placement = "right", trigger = "hover")
                  ),
                  tabPanel("Ongoing Project",
                           textInput("blurb1", "Blurb:", "Blurb"),
                           bsTooltip(id = "blurb1", title = "Enter a brief description of your project.", 
                                     placement = "right", trigger = "hover"),
                           textInput("caption1", "Name:", "Name"),
                           bsTooltip(id = "caption1", title = "Give your project a title.", 
                                     placement = "right", trigger = "hover"),
                           sliderInput("goalslider1",
                                       "goal amount:",
                                       min = 0,
                                       max = 5000,
                                       value = 0),
                           bsTooltip(id = "goalslider1", title = "Select goal amount for your project", 
                                     placement = "right", trigger = "hover"),
                           sliderInput("pledgeslider1",
                                       "Amount Pledge:",
                                       min = 0,
                                       max = 2000,
                                       value = 0),
                           bsTooltip(id = "pledgeslider1", title = "Select amount pledged for your project", 
                                     placement = "right", trigger = "hover"),
                           sliderInput("backersslider1",
                                       "Number of backers:",
                                       min = 0,
                                       max = 500,
                                       value = 0),
                           bsTooltip(id = "backersslider1", title = "Select number of backers your project", 
                                     placement = "right", trigger = "hover"),
                           sliderInput("Number_day_passedslider",
                                       "Days passed:",
                                       min = 0,
                                       max = 200,
                                       value = 0),
                           bsTooltip(id = "Number_day_passedslider", title = "Select number of days passed since beginning of your project", 
                                     placement = "right", trigger = "hover"),
                           sliderInput("durationslider1",
                                       "Duration:",
                                       min = 0,
                                       max = 200,
                                       value = 0),
                           bsTooltip(id = "durationslider1", title = "Select total duration in number of days for your project", 
                                     placement = "right", trigger = "hover")
                  )
                  
      ),
      actionButton("go", "Plot"),
      bsTooltip(id = "go", title = "Click on plot to check predictions", 
                placement = "right", trigger = "hover")
    ),
    mainPanel(
      htmlOutput('text1'),
      htmlOutput('text2'),
      
      strong("Results"),
      strong(textOutput("text") ),
      strong(textOutput("text3") ),
      plotOutput("plot"),
      plotOutput("plot1"),
      plotOutput("plot2"),
      plotOutput("plot3"),
      conditionalPanel(
        condition = "input.caption.value > 50",
        img(src='Image3.png', align = 'right')
      )
      
    )
  )
)
